Build push artifacts
nuclio/nuclio-ci pull request #6
Opened 2018-04-04 10:17 UTC by ilaykav

2018-04-04 11:59 UTC, pavius requested changes

2018-04-04 11:59 UTC, pavius commented on build_push_artifacts/build_push_artifacts.py
> +    if git_url is None:
1. why check only git_url? what about commit, branch
2. wrong error message

2018-04-04 11:59 UTC, pavius commented on build_push_artifacts/build_push_artifacts.py
> +    run_command(context, 'mkdir -p  /go/src/github.com/nuclio', '/')
use `NUCLIO_PATH`

2018-04-04 11:59 UTC, pavius commented on build_push_artifacts/build_push_artifacts.py
> +    repos_to_clone = ['https://github.com/v3io/v3io-go-http', 'https://github.com/nuclio/logger.git',
same convention as `{ }` (newline after `[`, etc

2018-04-04 11:59 UTC, pavius commented on build_push_artifacts/build_push_artifacts.py
> +    run_command(context, 'go get -d github.com/nuclio/v3io/...', NUCLIO_PATH)
what's wrong with just:
`go get github.com/v3io/v3io-go-http/... && go get github.com/nuclio/logger/... && go get github.com/nuclio/nuclio-sdk-go/... && go get github.com/nuclio/amqp/...` 
?

Why all the clones / moves?

2018-04-04 11:59 UTC, pavius commented on build_push_artifacts/build_push_artifacts.py
> +    for checkout_value in [git_branch, git_commit]:
nice. good application of not duplicating code

2018-04-04 11:59 UTC, pavius commented on build_push_artifacts/build_push_artifacts.py
> +def clone_and_build_repo(context, git_branch, git_commit=None, git_url=None):
i believe clone and build should be separate functions. dont see a reason why they should be one

2018-04-04 11:59 UTC, pavius commented on build_push_artifacts/build_push_artifacts.py
> +def get_images_tags(context):
if you add a `@` before the `for` to the makefile like so:
```
print-docker-images:
	@for image in $(IMAGES_TO_PUSH); do \
		echo $$image ; \
	done
```

The output will simply be:
```
nuclio/controller:latest-amd64
nuclio/playground:latest-amd64
nuclio/dashboard:latest-amd64
nuclio/processor-py2.7-alpine:latest-amd64
nuclio/processor-py2.7-jessie:latest-amd64
nuclio/processor-py3.6-alpine:latest-amd64
nuclio/processor-py3.6-jessie:latest-amd64
nuclio/handler-builder-golang-onbuild:latest-amd64
nuclio/processor-pypy2-5.9-jessie:latest-amd64
nuclio/handler-pypy2-5.9-jessie:latest-amd64
nuclio/processor-shell-alpine:latest-amd64
nuclio/handler-nodejs-alpine:latest-amd64
nuclio/handler-builder-dotnetcore-onbuild:latest-amd64
nuclio/handler-java:latest-amd64
nuclio/handler-builder-java-onbuild:latest-amd64
nuclio/user-builder-java-onbuild:latest-amd64
```

Then you should be simply be able to split @ newline. Not sure exactly what the filter is?

2018-04-04 11:59 UTC, pavius commented on build_push_artifacts/build_push_artifacts.py
> +def tag_and_push_images_to_local_registry(context, images_tags, registry_host_and_port):
I would just call this `push_images` - the whole "tag" and "local registry" are implementation details

2018-04-04 12:18 UTC, ilaykav commented on build_push_artifacts/build_push_artifacts.py
> +    if git_url is None:
git_branch and git_commit can be optional to let invocation of default branch / last commit easier, no?

2018-04-04 12:29 UTC, pavius commented on build_push_artifacts/build_push_artifacts.py
> +    if git_url is None:
It's up to us. And I think that defaulting to "latest" is not a convenience that we should offer, especially since > 99% of builds will be to a specific branch / commit

2018-04-05 20:44 UTC, pavius requested changes

2018-04-05 20:44 UTC, pavius commented on build_push_artifacts/build_push_artifacts.py
> +    for input_value in [git_url, git_commit, git_branch]:
`if None in [git_url, git_commit, git_branch]:`

2018-04-05 20:44 UTC, pavius commented on build_push_artifacts/build_push_artifacts.py
> +    run_command(context, f'export PATH=$PATH:/usr/local/go/bin && export GOPATH=/root/go \
Huh? All installations and such need to happen once, as part of image build... why is this here?

2018-04-08 15:34 UTC, pavius requested changes

2018-04-08 15:34 UTC, pavius commented on build_push_artifacts/build_push_artifacts.py
> +    run_command(context, f'git clone {git_url} {NUCLIO_PATH}', '/tmp')
why is /tmp here?

2018-04-08 15:34 UTC, pavius commented on build_push_artifacts/build_push_artifacts.py
> +            parse_result = parse.parse('{}/{}', image)
1. this should be a function like `parse_docker_image_name` that returns registry_url and image_name (don't do things like `x[1]` - it's not readable, things should be in named vars)
2. please make sure this will work for `aaa/bbb/ccc` as well (this is valid) - should return `aaa` and `bbb/ccc` and not `aaa/bbb`, `ccc`

2018-04-08 15:34 UTC, pavius commented on build_push_artifacts/build_push_artifacts.py
> +            context.logger.info_with('Tagged image finished', Tag_result=tag_result)
remove this logs, add them to run_command. run command should print exit code, stdout, stderr of command - this is _crucial_ information for all commands it runs

2018-04-08 16:14 UTC, merged